export const COLORS = {
bg: '#0a0a0f', card: '#13131a', card2: '#1a1a24',
accent: '#00e5a0', accent2: '#7c5cff', red: '#ff4d6d',
text: '#f0f0f8', muted: '#6b6b88', border: '#2a2a3a',
};

export const CATEGORIES = ['Food', 'Transport', 'Entertainment', 'Health', 'Housing', 'Salary', 'Other'];

export const CAT_EMOJIS = {
Food: '🍔', Transport: '🚗', Entertainment: '🎬',
Health: '❤️', Housing: '🏠', Salary: '💼', Other: '📦',
};

export const CAT_COLORS = {
Food: '#ff6b35', Transport: '#4ecdc4', Entertainment: '#ffe66d',
Health: '#ff6b9d', Housing: '#a8e6cf', Salary: '#00e5a0', Other: '#7c5cff',
};

export const DEFAULT_BUDGETS = {
Food: 20000, Transport: 10000, Entertainment: 8000,
Health: 5000, Housing: 50000, Salary: 0, Other: 15000,
};

export const TRANSLATIONS = {
en: {
// Nav
dashboard: 'Dashboard', transactions: 'Transactions', budget: 'Budget',
reminders: 'Reminders', savings: 'Savings', mercadopago: 'MP Import', charts: 'Charts',
// Transactions
addTx: 'Add Transaction', income: '💰 Income', expense: '💸 Expense',
desc: 'Description', amount: 'Amount ($)', category: 'Category', add: 'Add',
cancel: 'Cancel', delete: 'Delete', edit: 'Edit', save: 'Save',
deleteConfirm: 'Delete transaction?', deleteMsg: 'This action cannot be undone.',
noTx: 'No transactions yet.\nTap + to add one!',
// Dashboard
balance: 'Current Balance', totalIncome: 'Income', totalExpense: 'Expenses',
recentTx: 'Recent Transactions',
// Categories
cats: { Food:'Food', Transport:'Transport', Entertainment:'Entertainment', Health:'Health', Housing:'Housing', Salary:'Salary', Other:'Other' },
// Budget
budgetTitle: 'Budget by Category', over: 'Over!',
totalSpent: 'Total spent', totalBudget: 'Total budget', used: '% used',
noLimit: 'No limit', monthlyLimit: 'Monthly limit', setLimit: 'Set to 0 for no limit',
// Charts
chartsTitle: 'Charts',
lineChartTitle: 'Income vs Expenses (6 months)',
barChartTitle: 'Monthly comparison',
pieChartTitle: 'Expenses by category',
noExpenses: 'No expenses this month',
noData: 'No data yet.\nAdd transactions to see charts!',
chartIncome: 'Income', chartExpenses: 'Expenses',
evolution: '📈 Evolution', compare: '📊 Compare', categories: '🍩 Categories',
// Months
months: ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'],
// Reminders
addReminder: 'Add Reminder', reminderName: 'Payment Name',
reminderDue: 'Due Date (DD/MM/YYYY)', reminderAmt: 'Amount (optional)',
noReminders: 'No reminders yet.\nTap + to add one!',
statusOk: 'On time ✓', statusSoon: 'Due soon ⚠️', statusOverdue: 'Overdue ✗',
// Savings
savingsTitle: 'Savings',
tabSave: '🎯 Save', tabHistory: '📅 History', tabInvest: '💰 Invest', tabTips: '💡 Tips',
monthlyGoal: 'MONTHLY GOAL', noGoal: 'No goal set', setGoal: '+ Set goal', editGoal: '✏️ Edit',
savedSoFar: 'Saved', onTrack: 'On track! Keep it up to reach your goal',
offTrack: 'Behind. You need ', toGoal: ' more to reach your goal',
projectionTitle: 'MONTH-END PROJECTION',
projectionOver: "🎉 At this rate you'll exceed your goal by ",
projectionUnder: "⚠️ At this rate you'll be short by" ,
daysPassed: 'Days passed', daysLeft: 'Days left', dailySaving: 'Daily saving',
historyTitle: 'SAVINGS — LAST 6 MONTHS', ofGoal: 'of goal',
investTitle: 'INVESTMENT COMPARISON',
investSubtitle: 'Calculated on ',
monthSavings:  "(this month's savings)",
goalAmount: ' (monthly goal)',
updatingRates: 'Updating rates…', noConnection: '⚠️ No connection — approximate rates',
updatedAt: 'Updated at ',
monthlyReturn: 'Monthly return', yearlyReturn: 'Annual return',
usdEquiv: 'USD equivalent', salePriceLabel: 'Sale price',
disclaimer: '📌 Time deposit: official BCRA rate. MEP Dollar: daily rate via dolarapi.com. MP, Ualá and FCI: manually updated reference rates. FlowCash is not a financial advisor.',
tipsTitle: 'TIPS TO SAVE MORE',
tip1: 'Cut coffee and dining out costs. They can add up to a lot per month.',
tip2: 'Review unused subscriptions (streaming, apps). Cancel unnecessary ones.',
tip3: 'Make a list before grocery shopping. Avoid impulse buying.',
tip4: 'Calculate if using public transport some days saves you money.',
tip5: 'Pay credit cards on time to avoid interest.',
tip6: "Set aside savings as soon as you get paid, not what's left at month end.",
tip7: 'Check your electricity and gas bills. Small changes reduce consumption.',
ruleTitle: '📐 The 50/30/20 Rule',
ruleDesc: 'A simple guide to organize your finances:',
ruleNeeds: '50% Needs', ruleNeedsDesc: 'Rent, food, utilities',
ruleWants: '30% Wants', ruleWantsDesc: 'Dining out, entertainment, clothes',
ruleSavings: '20% Savings', ruleSavingsDesc: 'Emergency fund & investments',
noIncome: 'Add income to see your personalized calculation',
goalModalTitle: '🎯 Monthly savings goal',
goalModalDesc: 'How much do you want to save per month?',
goalModalBtn: 'Save goal',
tipOfDay: '💡 Tip of the day',
// Mercado Pago
mpTitle: 'Mercado Pago',
mpSubtitle: 'Import your transactions by reading your Gmail notifications',
mpConnected: '🟢 Gmail connected', mpDisconnected: '⚫ Gmail not connected',
mpLastSync: 'Last sync: ',
mpDisconnect: 'Disconnect',
mpDisconnectTitle: 'Disconnect Gmail',
mpDisconnectMsg: 'Are you sure you want to disconnect your Gmail account?',
mpPrivacyNote: '🔒 We only request ',
mpReadOnly: 'read-only',
mpPrivacyNote2: ' access to your Gmail. FlowCash never sends or deletes emails.',
mpConnect: '🔗 Connect Gmail',
mpSearchLabel: 'SEARCH TRANSACTIONS',
mpSearchBtn: '🔄 Search MP transactions',
mpSearching: ' Searching…',
mpFoundLabel: ' TRANSACTIONS FOUND',
mpSelectAll: 'All', mpSelectNone: 'None',
mpImportBtn: '✅ Import ',
mpImportDone: ' transactions imported successfully',
mpImportError: 'Could not import transactions',
mpNoSelection: 'No selection',
mpNoSelectionMsg: 'Select at least one transaction',
mpEmpty: 'No MP transactions found in the last ',
mpEmptyDays: ' days',
mpEmptyHint: 'Try increasing the search period',
mpPrivacyTitle: '🔒 Your privacy',
mpPrivacyText: 'FlowCash accesses your Gmail with read-only permission. It only reads Mercado Pago notification emails to detect amounts. It never reads other emails, stores your password, or sends emails on your behalf.',
// Auth / Login
logoSub: 'Control your finances 💸',
googleBtn: 'Continue with Google',
loginMode: 'Log in',
registerMode: 'Register',
emailLabel: 'EMAIL',
passwordLabel: 'PASSWORD',
passwordPlaceholder: 'Min. 6 characters',
forgotPassword: 'Forgot your password?',
emailRequired: 'Please fill in all fields',
invalidCredential: 'Wrong email or password',
emailInUse: 'Email already registered',
weakPassword: 'Password must be at least 6 characters',
authError: 'An error occurred, please try again',
resetEmailSent: '✅ We sent you an email to reset your password',
noAccountEmail: 'Enter your email above first',
noAccountFound: 'No account found with that email',
logout: 'Log out',
loginBtn: 'Log in',
registerBtn: 'Create account',
editTx: '✏️ Edit Transaction',
saveChanges: 'Save changes',
descPlaceholder: 'E.g.: Salary, Supermarket...',
},
es: {
// Nav
dashboard: 'Inicio', transactions: 'Movimientos', budget: 'Presupuesto',
reminders: 'Recordatorios', savings: 'Ahorros', mercadopago: 'MP Import', charts: 'Gráficos',
// Transactions
addTx: 'Agregar Movimiento', income: '💰 Ingreso', expense: '💸 Gasto',
desc: 'Descripción', amount: 'Monto ($)', category: 'Categoría', add: 'Agregar',
cancel: 'Cancelar', delete: 'Eliminar', edit: 'Editar', save: 'Guardar',
deleteConfirm: '¿Eliminar movimiento?', deleteMsg: 'Esta acción no se puede deshacer.',
noTx: 'Sin movimientos aún.\n¡Tocá + para agregar!',
// Dashboard
balance: 'Saldo Actual', totalIncome: 'Ingresos', totalExpense: 'Gastos',
recentTx: 'Últimos Movimientos',
// Categories
cats: { Food:'Comida', Transport:'Transporte', Entertainment:'Entretenimiento', Health:'Salud', Housing:'Vivienda', Salary:'Sueldo', Other:'Otro' },
// Budget
budgetTitle: 'Presupuesto por Categoría', over: '¡Excedido!',
totalSpent: 'Total gastado', totalBudget: 'Presupuesto total', used: '% usado',
noLimit: 'Sin límite', monthlyLimit: 'Límite mensual', setLimit: 'Poné 0 para sin límite',
// Charts
chartsTitle: 'Gráficos',
lineChartTitle: 'Ingresos vs Gastos (6 meses)',
barChartTitle: 'Comparación mensual',
pieChartTitle: 'Gastos por categoría',
noExpenses: 'Sin gastos este mes',
noData: 'Sin datos aún.\n¡Agregá movimientos para ver gráficos!',
chartIncome: 'Ingresos', chartExpenses: 'Gastos',
evolution: '📈 Evolución', compare: '📊 Comparar', categories: '🍩 Categorías',
// Months
months: ['Ene','Feb','Mar','Abr','May','Jun','Jul','Ago','Sep','Oct','Nov','Dic'],
// Reminders
addReminder: 'Agregar Recordatorio', reminderName: 'Nombre del pago',
reminderDue: 'Fecha de vencimiento (DD/MM/YYYY)', reminderAmt: 'Monto (opcional)',
noReminders: 'Sin recordatorios.\n¡Tocá + para agregar!',
statusOk: 'Al día ✓', statusSoon: 'Vence pronto ⚠️', statusOverdue: 'Vencido ✗',
// Savings
savingsTitle: 'Ahorros',
tabSave: '🎯 Ahorro', tabHistory: '📅 Historial', tabInvest: '💰 Invertir', tabTips: '💡 Consejos',
monthlyGoal: 'META MENSUAL', noGoal: 'Sin meta', setGoal: '+ Fijar meta', editGoal: '✏️ Editar',
savedSoFar: 'Ahorrado', onTrack: '¡Vas bien! Seguí así para cumplir la meta',
offTrack: 'Vas atrasado. Te faltan ', toGoal: ' para la meta',
projectionTitle: 'PROYECCIÓN AL FIN DE MES',
projectionOver: '🎉 A este ritmo vas a superar tu meta en ',
projectionUnder: '⚠️ A este ritmo te van a faltar ',
daysPassed: 'Días pasados', daysLeft: 'Días restantes', dailySaving: 'Ahorro diario',
historyTitle: 'AHORRO ÚLTIMOS 6 MESES', ofGoal: 'de la meta',
investTitle: 'COMPARACIÓN DE INVERSIONES',
investSubtitle: 'Calculado sobre ',
monthSavings: ' (ahorro del mes)',
goalAmount: ' (meta mensual)',
updatingRates: 'Actualizando tasas…', noConnection: '⚠️ Sin conexión — tasas aproximadas',
updatedAt: 'Actualizado a las ',
monthlyReturn: 'Ganancia mensual', yearlyReturn: 'Ganancia anual',
usdEquiv: 'Equivalente en USD', salePriceLabel: 'Cotización venta',
disclaimer: '📌 Plazo fijo: tasa oficial BCRA en tiempo real. Dólar MEP: cotización del día via dolarapi.com. MP, Ualá y FCI: tasas referenciales actualizadas manualmente. FlowCash no es asesor financiero.',
tipsTitle: 'CONSEJOS PARA AHORRAR MÁS',
tip1: 'Reducí gastos de café y salidas. Pueden sumar hasta $20.000 al mes.',
tip2: 'Revisá suscripciones que no usás (streaming, apps). Cancelá las innecesarias.',
tip3: 'Hacé una lista antes de ir al supermercado. Evitás compras impulsivas.',
tip4: 'Calculá si te conviene usar transporte público algunos días.',
tip5: 'Pagá las tarjetas al vencimiento para evitar intereses.',
tip6: 'Separé el ahorro apenas cobrás, no lo que sobre a fin de mes.',
tip7: 'Revisá tu factura de luz y gas. Pequeños cambios bajan el consumo.',
ruleTitle: '📐 Regla del 50/30/20',
ruleDesc: 'Una guía simple para organizar tus finanzas:',
ruleNeeds: '50% Necesidades', ruleNeedsDesc: 'Alquiler, comida, servicios',
ruleWants: '30% Deseos', ruleWantsDesc: 'Salidas, entretenimiento, ropa',
ruleSavings: '20% Ahorro', ruleSavingsDesc: 'Emergencias e inversiones',
noIncome: 'Agregá ingresos para ver el cálculo personalizado',
goalModalTitle: '🎯 Meta de ahorro mensual',
goalModalDesc: '¿Cuánto querés ahorrar por mes?',
goalModalBtn: 'Guardar meta',
tipOfDay: '💡 Consejo del día',
// Mercado Pago
mpTitle: 'Mercado Pago',
mpSubtitle: 'Importá tus movimientos leyendo las notificaciones de tu Gmail',
mpConnected: '🟢 Gmail conectado', mpDisconnected: '⚫ Gmail no conectado',
mpLastSync: 'Última sync: ',
mpDisconnect: 'Desconectar',
mpDisconnectTitle: 'Desconectar Gmail',
mpDisconnectMsg: '¿Seguro que querés desconectar tu cuenta de Gmail?',
mpPrivacyNote: '🔒 Solo pedimos permiso de ',
mpReadOnly: 'lectura',
mpPrivacyNote2: ' de tu Gmail. FlowCash nunca envía ni borra emails.',
mpConnect: '🔗 Conectar Gmail',
mpSearchLabel: 'BUSCAR MOVIMIENTOS',
mpSearchBtn: '🔄 Buscar movimientos de MP',
mpSearching: ' Buscando…',
mpFoundLabel: ' MOVIMIENTOS ENCONTRADOS',
mpSelectAll: 'Todos', mpSelectNone: 'Ninguno',
mpImportBtn: '✅ Importar ',
mpImportDone: ' transacciones importadas correctamente',
mpImportError: 'No se pudieron importar las transacciones',
mpNoSelection: 'Sin selección',
mpNoSelectionMsg: 'Seleccioná al menos una transacción',
mpEmpty: 'No se encontraron movimientos de MP en los últimos ',
mpEmptyDays: ' días',
mpEmptyHint: 'Probá aumentar el período de búsqueda',
mpPrivacyTitle: '🔒 Tu privacidad',
mpPrivacyText: 'FlowCash accede a tu Gmail con permiso de solo lectura. Solo lee los emails de Mercado Pago para detectar montos. Nunca lee otros emails, ni guarda tu contraseña, ni envía emails en tu nombre.',
// Auth / Login
logoSub: 'Tus finanzas, bajo control 💸',
googleBtn: 'Continuar con Google',
loginMode: 'Iniciar sesión',
registerMode: 'Registrarse',
emailLabel: 'EMAIL',
passwordLabel: 'CONTRASEÑA',
passwordPlaceholder: 'Mínimo 6 caracteres',
forgotPassword: '¿Olvidaste tu contraseña?',
emailRequired: 'Completá todos los campos',
invalidCredential: 'Email o contraseña incorrectos',
emailInUse: 'El email ya está registrado',
weakPassword: 'La contraseña debe tener al menos 6 caracteres',
authError: 'Ocurrió un error, intentá de nuevo',
resetEmailSent: '✅ Te enviamos un email para restablecer tu contraseña',
noAccountEmail: 'Primero ingresá tu email arriba',
noAccountFound: 'No existe una cuenta con ese email',
logout: 'Salir',
loginBtn: 'Entrar',
registerBtn: 'Crear cuenta',
editTx: '✏️ Editar movimiento',
saveChanges: 'Guardar cambios',
descPlaceholder: 'Ej: Sueldo, Supermercado...',
},
};